name: Deploy EasySVGLab to Aruba

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp index.html deploy/
          cp style.css deploy/
          cp app.js deploy/
          cp rotation-arrow.svg deploy/

      - name: Deploy to Aruba via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
